script.Parent.ClickDetector.MouseClick:Connect(function()
	game.Workspace.Buzzerwall1.BrickColor = BrickColor.new("Bright yellow")
	game.Workspace.Buzzerwall2.BrickColor = BrickColor.new("Bright yellow")
	game.Workspace.Buzzerwall3.BrickColor = BrickColor.new("Bright yellow")
	game.Workspace.Buzzerwall4.BrickColor = BrickColor.new("Bright yellow")
	game.Workspace.Buzzerwall5.BrickColor = BrickColor.new("Bright yellow")
	game.Workspace.X.Part.BrickColor = BrickColor.new("Bright yellow")
	game.Workspace.X.Part1.BrickColor = BrickColor.new("Bright yellow")
	game.Workspace.X2.Part.BrickColor = BrickColor.new("Bright yellow")
	game.Workspace.X2.Part1.BrickColor = BrickColor.new("Bright yellow")
	game.Workspace.X3.Part.BrickColor = BrickColor.new("Bright yellow")
	game.Workspace.X3.Part1.BrickColor = BrickColor.new("Bright yellow")
	game.Workspace.X4.Part.BrickColor = BrickColor.new("Bright yellow")
	game.Workspace.X4.Part1.BrickColor = BrickColor.new("Bright yellow")
	game.Workspace.XX.Part.BrickColor = BrickColor.new("Bright yellow")
	game.Workspace.XX.Part1.BrickColor = BrickColor.new("Bright yellow")
	game.Workspace.XX2.Part.BrickColor = BrickColor.new("Bright yellow")
	game.Workspace.XX2.Part1.BrickColor = BrickColor.new("Bright yellow")
	game.Workspace.XX3.Part.BrickColor = BrickColor.new("Bright yellow")
	game.Workspace.XX3.Part1.BrickColor = BrickColor.new("Bright yellow")
	game.Workspace.XX4.Part.BrickColor = BrickColor.new("Bright yellow")
	game.Workspace.XX4.Part1.BrickColor = BrickColor.new("Bright yellow")
	game.Workspace.stagex.Part.BrickColor = BrickColor.new("Bright yellow")
	game.Workspace.stagex.Part1.BrickColor = BrickColor.new("Bright yellow")
end)
