script.Parent.ClickDetector.MouseClick:Connect(function()
	game.Workspace.X3.Part.BrickColor = BrickColor.new("Really red")
	game.Workspace.X3.Part1.BrickColor = BrickColor.new("Really red")
	game.Workspace.XX3.Part.BrickColor = BrickColor.new("Really red")
	game.Workspace.XX3.Part1.BrickColor = BrickColor.new("Really red")
	game.Workspace.Buzzerwall1.BrickColor = BrickColor.new("Really red")
	game.Workspace.Buzzerwall2.BrickColor = BrickColor.new("Really red")
	game.Workspace.Buzzerwall3.BrickColor = BrickColor.new("Really red")
	game.Workspace.Buzzerwall4.BrickColor = BrickColor.new("Really red")
	game.Workspace.Buzzerwall5.BrickColor = BrickColor.new("Really red")
	game.Workspace.stagex.Part.BrickColor = BrickColor.new("Really red")
	game.Workspace.stagex.Part1.BrickColor = BrickColor.new("Really red")
end)
